# Generated by Django 3.1.2 on 2021-05-03 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speaker_verification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='embedding',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
    ]
